"""added indexes for filters&sort

Revision ID: 4178ff722cc6
Revises: 50776f7606ab
Create Date: 2026-04-30 13:02:41.733487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4178ff722cc6'
down_revision = '50776f7606ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_tasks_assignee_id', 'tasks', ['assignee_id'], unique=False)
    op.create_index('idx_tasks_assignee_status', 'tasks', ['assignee_id', 'status'], unique=False)
    op.create_index('idx_tasks_created_at', 'tasks', ['created_at'], unique=False)
    op.create_index('idx_tasks_owner_created', 'tasks', ['owner_id', 'created_at'], unique=False)
    op.create_index('idx_tasks_owner_id', 'tasks', ['owner_id'], unique=False)
    op.create_index('idx_tasks_owner_status', 'tasks', ['owner_id', 'status'], unique=False)
    op.create_index('idx_tasks_status', 'tasks', ['status'], unique=False)
    op.create_index('idx_tasks_status_created', 'tasks', ['status', 'created_at'], unique=False)
    op.create_index('idx_tasks_updated_at', 'tasks', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tasks_updated_at', table_name='tasks')
    op.drop_index('idx_tasks_status_created', table_name='tasks')
    op.drop_index('idx_tasks_status', table_name='tasks')
    op.drop_index('idx_tasks_owner_status', table_name='tasks')
    op.drop_index('idx_tasks_owner_id', table_name='tasks')
    op.drop_index('idx_tasks_owner_created', table_name='tasks')
    op.drop_index('idx_tasks_created_at', table_name='tasks')
    op.drop_index('idx_tasks_assignee_status', table_name='tasks')
    op.drop_index('idx_tasks_assignee_id', table_name='tasks')
    # ### end Alembic commands ###
