"""added constrains

Revision ID: 50776f7606ab
Revises: e78471c267ae
Create Date: 2026-04-30 12:53:47.075143

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '50776f7606ab'
down_revision = 'e78471c267ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'content',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('comments', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('comments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.drop_constraint('comments_task_id_fkey', 'comments', type_='foreignkey')
    op.drop_constraint('comments_user_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comments', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.alter_column('task_history', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('task_history', 'field_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('task_history', 'changed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_task_history_id'), 'task_history', ['id'], unique=False)
    op.drop_constraint('task_history_changed_by_fkey', 'task_history', type_='foreignkey')
    op.drop_constraint('task_history_task_id_fkey', 'task_history', type_='foreignkey')
    op.create_foreign_key(None, 'task_history', 'users', ['changed_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'task_history', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.alter_column('tasks', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tasks', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('tasks', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('tasks_owner_id_fkey', 'tasks', type_='foreignkey')
    op.drop_constraint('tasks_assignee_id_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tasks', 'users', ['assignee_id'], ['id'], ondelete='SET NULL')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_assignee_id_fkey', 'tasks', 'users', ['assignee_id'], ['id'])
    op.create_foreign_key('tasks_owner_id_fkey', 'tasks', 'users', ['owner_id'], ['id'])
    op.alter_column('tasks', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tasks', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tasks', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'task_history', type_='foreignkey')
    op.drop_constraint(None, 'task_history', type_='foreignkey')
    op.create_foreign_key('task_history_task_id_fkey', 'task_history', 'tasks', ['task_id'], ['id'])
    op.create_foreign_key('task_history_changed_by_fkey', 'task_history', 'users', ['changed_by'], ['id'])
    op.drop_index(op.f('ix_task_history_id'), table_name='task_history')
    op.alter_column('task_history', 'changed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('task_history', 'field_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('task_history', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_user_id_fkey', 'comments', 'users', ['user_id'], ['id'])
    op.create_foreign_key('comments_task_id_fkey', 'comments', 'tasks', ['task_id'], ['id'])
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.alter_column('comments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comments', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comments', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
