"""refactored using mapping

Revision ID: 524c232f4d62
Revises: 4178ff722cc6
Create Date: 2026-05-08 00:36:42.089153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '524c232f4d62'
down_revision = '4178ff722cc6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
