"""added roles for users

Revision ID: 79121d12d5c4
Revises: 524c232f4d62
Create Date: 2026-05-15 23:40:26.600478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79121d12d5c4'
down_revision = '524c232f4d62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
